import 'dotenv/config';
import {Agent , run , tool} from "@openai/agents";
import {z} from 'zod';
import fs from 'node:fs/promises';
import { Resend } from 'resend';
import readline from 'readline';

const resend = new Resend(process.env.RESEND_API_KEY);




const fetchPlanDetails=tool({
    name:"fetch_plan_details_tool",
    description:"Shares plan details with users",
    parameters:z.object({}),
    execute:async function(){
    return [
    { plan_id: '1', price_inr: 399, speed: '30MB/s' },
    { plan_id: '2', price_inr: 999, speed: '100MB/s' },
    { plan_id: '3', price_inr: 1499, speed: '200MB/s' },
    ];
},
    
});

const processRefund =tool({
    name:"process_refund_tool",
    description:"Processes refund of user ",
    parameters:z.object({
        plan_id:z.string().describe("customer's plan id") ,
        customer_id:z.string().describe("customer's customer_id for which refund needs to be processed"),
        description:z.string().describe("Reason for refund initiation")
    }),
    execute:async function({plan_id , customer_id ,description}){
        await fs.appendFile(
            `${customer_id}_refund.txt`,
            `Refund for Customer  ID ${customer_id} for  plan Id : ${plan_id} for reason ${description}`,
            'utf-8'
        );
        return  {refundIssued:true};
    },


});




const emailTool=tool({
    name:"send_email_to_user",
    description:"Send refund confirmation email to user",
    parameters:z.object({
        name:z.string().describe("name of user"),
        email:z.string().describe("email address of user"),
        customer_id:z.string().describe("customer Id"),
        plan_id:z.string().describe("plan id"),
        description:z.string().describe("Reason for refund")
    }),
    execute:async function ({name, email, customer_id, plan_id, description}) {
        const htmlTemplate = `
      <div style="font-family: Arial, sans-serif; line-height: 1.6;">
        <h2 style="color:#2c3e50;">Refund Confirmation - Quantam Networks</h2>

        <p>Hi ${name},</p>

        <p>Your refund request has been successfully processed.</p>

        <div style="background:#f4f6f8; padding:15px; border-radius:8px; margin:20px 0;">
          <h3 style="margin-top:0; color:#27ae60;">Refund Details</h3>
          <p><strong>Customer ID:</strong> ${customer_id}</p>
          <p><strong>Plan ID:</strong> ${plan_id}</p>
          <p><strong>Reason:</strong> ${description}</p>
          <p><strong>Status:</strong> <span style="color:#27ae60;">✓ Approved</span></p>
        </div>

        <p>The refund amount will be credited to your original payment method within 5-7 business days.</p>

        <p style="margin-top:20px;">
          This is a system-generated email automatically generated by an AI Agent 
          built using the <strong>OpenAI Agent SDK</strong>.
          No human intervention was involved in sending this message.
        </p>

        <p>Best Regards,<br/>
        <strong>Customer Support - Quantam Networks</strong></p>

        <hr/>
        <small style="color:gray;">
          Generated on ${new Date().toLocaleString()}
        </small>
      </div>
    `;
        try {
            const data = await resend.emails.send({
                from: 'Quantam Networks <onboarding@resend.dev>',
                to: [email],
                subject: 'Refund Confirmation - Quantam Networks',
                html: htmlTemplate
            });

            console.log('Email sent:', data);
            return `Refund confirmation email sent successfully to ${email}`;
        } catch (error) {
            console.error('Email error:', error);
            return `Failed to send email to ${email}: ${error.message}`;
        }
    }
})

const refundAgent= new Agent({
    name:"process_refund_agent",
    instructions:"You are a refund agent who processes users refund on basis of there plan which they have and customeId which they provides. After processing the refund, send a confirmation email to the user.",
    tools:[processRefund, emailTool],
});

const salesAgent= new Agent({
    name:"sales_agent",
    instructions:"respond user with plan details which we have. Also Negotiate with user when user try to ask for refund  ",
    tools:[fetchPlanDetails]
});



const customerSupportAgent = new Agent (
    {
        name:"customer_support_agent",
        instructions:` 1.You are a customer support agent for Internet provider named Quantam_Networks 
        2. Users will ask you query related to there services respond them properly
        3. Remember the name and email if user has provided any
        4. if user asks for plan details calls sales_agent
        5. if user wants refund for there plan then call process_refund_agent
        6. Remember planid, customerid, email, and reason which users provide for refund 
        7. After refund is processed, ensure a confirmation email is sent to the user
        8. For processing refund custonerid , email ,planid  and reason all are mandatory .without this you cant refund money or send refund mail
        9. There should be a valid reason for refund .
        10. Negotiate with user before doing refund 
        11. If user is facing any technical or general issue try to resolve it . 
        `,
        tools:[salesAgent.asTool({
            toolName:"sales_expert_agent",
            toolDescription:'Handles users query related to internet palans and share plan details with user',
        }),
        refundAgent.asTool({
            toolName:"process_refund_agent",
            toolDescription:"process refund of users when user ask for refund "
        })

    ]
    }

)

// Create readline interface for interactive input
const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
});

// Store conversation history
let conversationHistory = [];

function askQuestion(prompt) {
    return new Promise((resolve) => {
        rl.question(prompt, (answer) => {
            resolve(answer);
        });
    });
}

async function main() {
    console.log("\n=== Quantam Networks Customer Support ===\n");
    console.log("Welcome! I'm your AI customer support agent.");
    console.log("Type 'exit' or 'quit' to end the conversation.\n");

    while (true) {
        const userInput = await askQuestion("You: ");

        // Check if user wants to exit
        if (userInput.toLowerCase() === 'exit' || userInput.toLowerCase() === 'quit') {
            console.log("\nThank you for contacting Quantam Networks. Have a great day!");
            rl.close();
            break;
        }

        // Skip empty input
        if (!userInput.trim()) {
            continue;
        }

        try {
            // Run the agent with user input
            const result = await run(customerSupportAgent, userInput);
            
            // Display agent's response
            console.log("\nAgent:", result.finalOutput);
            console.log(""); // Empty line for readability

        } catch (error) {
            console.error("\nError:", error.message);
            console.log(""); // Empty line for readability
        }
    }
}

// Start the interactive conversation
main();





