
import { Resend } from 'resend';
const resend = new Resend(process.env.RESEND_API_KEY);
import 'dotenv/config';
import {Agent , run , tool} from "@openai/agents";
import {z} from 'zod';
import axios from 'axios';


const GetWeatherResultSchema = z.object({
  city: z.string().describe('name of the city'),
  degree_c: z.number().describe('the degree celcius of the temp'),
  condition: z.string().optional().describe('condition of the weather'),
});

const getWeatherTool=tool({
  name:"get_weather_details",
  description:"Give details of weather of the city which users ask for.",
  parameters:z.object({
    city:z.string().describe('Name of the city')
  }),
  execute:async function({city}){
    const api=`https://wttr.in/${city.toLowerCase()}?format=%C+%t`;
   const response= axios.get(api ,{responseType :'text'});
    return  `The weather in ${city} is ${(await response).data}`
  },

});

const emailTool =tool({
  name:"send_email_to_user",
  description:"The city for which user have asked weather. Share weather details with that user",
  parameters:z.object({
   email: z.string().describe("Email address"),
    weatherReport: z.string().describe("Weather details to send"),
    name:z.string().describe("Name of the user ")
  }),
  execute:async function({email  , weatherReport , name}){
    const htmlTemplate = `
      <div style="font-family: Arial, sans-serif; line-height: 1.6;">
        <h2 style="color:#2c3e50;">Weather Update</h2>

        <p>Hi ${name},</p>

        <p>Here is the weather report you requested:</p>

        <div style="background:#f4f6f8; padding:15px; border-radius:8px;">
          <strong>${weatherReport}</strong>
        </div>

        <p style="margin-top:20px;">
          This is a system-generated email automatically generated by an AI Agent 
          built using the <strong>OpenAI Agent SDK</strong>.
          No human intervention was involved in sending this message.
        </p>

        <p>Best Regards,<br/>
        <strong>Weather AI Agent</strong></p>

        <hr/>
        <small style="color:gray;">
          Generated on ${new Date().toLocaleString()}
        </small>
      </div>
    `;
    try {
    const data = await resend.emails.send({
      from: ' Weather  Agent  <onboarding@resend.dev>',
      to: [email],
      subject: 'Weather details ',
      html: htmlTemplate
    });

    console.log(data);
  } catch (error) {
    console.error(error);
  }
  return `Email  send to ${email} `;

  },
  
});

const agent = new Agent({
  name:'weatherAgent',
 instructions: `
You are a Weather Assistant.

1. If user asks for weather, call get_weather_details.
2. If user provides their name, remember it.
3. If user provides email, call send_email_to_user.
4. Pass name, email and weatherReport to the email tool. 
Always use tools when required.
`,
tools:[getWeatherTool ,emailTool],
 

});


async function main (query =''){
  const result=await run (agent ,query);
  console.log("Result:" , result.finalOutput);
}
main("Hi Harsh here What is temperature of shimla ? and send weather report  to   srivastavah240@gmail.com ");





// const useremail= 
// (async function() {
//   try {
//     const data = await resend.emails.send({
//       from: 'AI Agent  <onboarding@resend.dev>',
//       to: ['srivastavah240@gmail.com'],
//       subject: 'Hello World',
//       html: '<strong>It works!</strong>'
//     });

//     console.log(data);
//   } catch (error) {
//     console.error(error);
//   }
// })();